### ISSUE TITLE
About performance

### ISSUE THREAD

**Issue by stream-iori** [vert-x3/vertx-sync#5]
Hi all
I have run the benchmark of this project, and found SyncBenchmarkVerticle is slower than AsyncBenchmarkVerticle about 7-8x, does this is normal?

I am using quasar 0.7.3:jdk8. 
all the benchmark had running at least 15 min for warm up jvm.

**Comment by pron** [comment]
It's quite possible. The reason is simply that `SomeAsyncInterfaceImpl` doesn't do anything. It's basically a no-op, so the benchmark measures nothing but scheduling overhead. If you have an overhead of 2ns vs. 15ns you'd get a 7-8x slowdown. Of course, if the actual work takes 1us, the difference drops down to 1%. What matters is how big is the added overhead _relative to the work you normally do in async calls_.

Have `SomeAsyncInterfaceImpl` do some work, like sorting an array of random numbers and then measure.

**Comment by purplefox** [comment]
What pron said. The purpose of the benchmark is to measure the overhead. For most users this won't be noticeable.

**Comment by stream-iori** [comment]
Ok, i get it.
I try to mock some overhead work, could i using `Strand.sleep(100)` in method of `asyncMethod` ?
I did it, but there are no any info put out, unless comment `Strand.sleep(100)`.

Any way i have make sorting an array in `asyncMethod`, and i found `rate` value both in `SyncBenchmark` and `AsyncBenchmark` is very close. :)
